msg_themes = {'out_of_date_version': "la version du DPE ou de l'audit n'est pas valable actuellement.",
              'invalid_date_etablissement': "la date d'etablissement du DPE ou de l'audit est supérieure à la date du jour et donc invalide.",
              'warning_date_etablissement_visite': "la date de visite de l'audit est postérieure ou égale à la date d'etablissement.",
              'bad_model': "le modèle DPE ou audit n'est pas valide.",
              'bad_enum_tv': 'mauvaise correspondance enum avec table de valeur',
              'bad_value_tv': 'mauvaise correspondance valeur avec table de valeur',
              'bad_value': "la valeur d'une donnée intermediaire ne correspond pas aux données d'entrées correspondantes",
              "missing_required_element": "element requis manquant dans le modèle de données.",
              "mutually_exclusive": "elements mutuellement exclusifs.",
              "forbidden_element": "element interdit présent dans le modèle de données",
              "bad_installation_cfg": "il existe des problèmes de structure dans l'installation de chauffage (générateurs ou émetteurs manquants ou incohérents)",
              "inconsistent_regulation": "le rendement de régulation ne correspond pas au type de régulation attendu",
              "bad_surface": "une surface est incohérente avec les autres surfaces déclarées.",
              "bad_by_energy_output": "les sorties par type d'énergie ne correspondent pas aux données déclarées sur les systèmes de chauffage et d'ECS.",
              "bad_ef_conso_calculation": "la somme des consommations par type d'énergie n'est pas cohérente avec les consommations en énergie finale 5 usages totales.",
              "bad_ep_conso_calculation": "la somme des consommations par type d'énergie convertie en énergie primaire, n'est pas cohérente avec les consommations en primaire finale 5 usages totales.",
              "bad_rset_rsee": "le fichier rset/rsee fourni en entrée est invalide",
              "anomaly": "saisie anormale d'un élément",
              "anomaly_pont_thermique": "saisie anormale concernant les ponts thermiques.",
              "incoherence_enveloppe": "saisie incohérente d'un élément d'enveloppe.",
              "incoherence_systeme": "saisie incohérente d'un élément système.",
              "address_anomaly": "l'adresse du bien semble imprécise ou érronée.",
              "geocoding_error": "les données renseignées ne correspondent pas au retour de l'API de la BAN ",
              "bad_etiquette_calculation": "le calcul de l'étiquette DPE ou de l'étiquette GES DPE est incohérent avec les données de consommation/emission_ges. ",
              "error_generateur_cascade_valeur_0": "une donnée de sortie est saisie à 0 pour un générateur qui n'est pas en cascade avec priorité et non prioritaire.",
              "error_generateur_cascade_order": "il manque un générateur cascade avec un ordre de priorité 1",
              "error_conso_0": "une consommation est égale à 0 et ne correspond à aucun cas particulier qui permet ce type de saisie",
              "error_cle_repartition":"une installation ou un objet système bâtiment ne spécifie pas sa clé de répartition dans le cas d'un dpe appartement à partir de l'immeuble",
              "error_missing_dpe_immeuble_associe": "il manque le champ dpe_immeuble_associe pour un DPE appartement à partir de l'immeuble ",
              "error_duplicate_reference":"il existe des références non uniques dans le DPE transmis.",
              "error_methode_application": "il existe des erreurs dans le choix de la méthode d'application du DPE.",
              "error_date_arrete_reseau_chaleur": "il existe un problème dans la date de l'arrêté de réseau de chaleur en place dans le logiciel",
              "warning_identifiant_reseau": "l'identifiant réseau utilisé n'est pas répertorié dans la table de l'arrêté réseau de chaleur correspondant.",
              "error_duplicate_etape":"il existe des étapes non uniques dans un des scénarios de l'audit.",
              "error_missing_reference":"il existe des références dans travaux_collection/reference_collection qui n'existent pas dans le logement.",
              "error_missing_etape":"une étape de travaux obligatoire est manquante dans l'audit.",
              "warning_missing_etape":"une étape de travaux est manquante dans l'audit.",
              "warning_missing_recommandation":"les recommandations auditeurs (encadrés « observations » dans la trame) sont manquantes.",
              "warning_class_etape_intermediaire":"la classe DPE de l'étape intermédiaire du « scénario multi étapes principal » n'est pas suffisamment bonne pour respecter les exigences de l'audit règlementaire",
              "warning_too_many_etape":"un des scénarios contient plus de 3 étapes, ce qui rends techniquement difficile l'atteinte de la classe B",
              "error_missing_scenario":"un des scénarios obligatoires est manquant dans l'audit.",
              "error_number_etape":"le nombre d'étapes n'est pas compatible avec le type de scénario (« scénario en une étape principal » et « scénario multi étapes principal »).",
              "error_missing_etape_travaux":"l'objet « etape_travaux » est manquant dans le logement.",
              "error_present_etape_travaux":"l'objet « etape_travaux » est present dans le logement alors qu'il s'agit de l'« état initial ».",
              "error_class_etape_finale":"la classe DPE de l'étape finale d'un des scénarios principaux n'est pas suffisamment bonne pour respecter les exigences de l'audit règlementaire",
              "warning_class_etape_finale":"la classe DPE de l'étape finale d'un des scénarios complémentaires n'est pas suffisamment bonne pour respecter les exigences de l'audit règlementaire",
              "error_etape_travaux_dpe":"un element de étape_travaux n'est pas cohérent avec la sortie du DPE",
              "error_etape_travaux_cout":"le coût déclaré dans étape_travaux n'est pas cohérent avec la somme des coûts des travaux de l'étape (travaux induits inclus)",
              "warning_cost_to_zero":"un ou plusieurs travaux dans « travaux_collection » ont leur balise - cout à 0 €",
              "warning_shab_division":"une ou plusieurs balises de « etape_travaux » ont des écarts très importants (facteur 10) avec les sorties dpe - probablement du à un oubli de division par la shab.",
              "error_etat_composant":"il existe des incohérences entre la valeur les valeurs des « enum_etat_composant_id » et le l' « enum_etape_id » du logement.",
              "error_maj_and_replace":"l'audit ne peut pas être à la fois mis à jour et remplacé",
              "warning_missing_work":"les 6 postes de travaux n'ont pas été tous traités dans l'un des scenarios principaux, alors qu'il s'agit d'une dérogation",
              "warning_missing_dpe_number":"le numéro DPE est absent alors qu'il s'agit d'un audit règlementaire",
              "error_derogation_ventilation":"Incohérence sur la dérogation ventilation, entre ce qui est renseigné avec enum_derogation_ventilation_id et avec enum_etat_ventilation_id",
              "warning_ubat_base": "pour une étape finale d'un des scénarios principaux, le Ubat projet est supérieur au Ubat base, ce qui n'est pas BCC réno compatible",
              "warning_etat_ventilation": "pour une étape de travaux, l'état de la ventilation n'est pas fonctionnelle, ce qui n'est pas BCC réno compatible",
              "error_caracteristiques_travaux_missing":"un ou plusieurs travaux dans « travaux_collection » ne contiennent pas la balise 'caracteristiques_travaux' alors qu'ils font partis des types de travaux où elle est exigée",
              "error_caracteristiques_travaux_presence":"un ou plusieurs travaux dans « travaux_collection » contiennent la balise 'caracteristiques_travaux' alors qu'ils ne font pas partis des types de travaux où elle est demandée",
              "error_caracteristiques_travaux_consistency": "un ou plusieurs travaux dans « travaux_collection » ont une incohérence entre le type de travaux déclaré dans 'enum_type_travaux_id' et celui déclaré dans 'caracteristiques_travaux'",
              "error_travaux_cout_fourchette": "une fourchette de coûts est mal déclarée, puisque l'une des deux balises nécessaires : 'cout_max', 'cout_min', est manquante",
              "error_travaux_cout_missing": "aucun coûts n'est déclaré. Merci de renseigner soit 'cout', soit 'cout_min' et 'cout_max'",
              "error_travaux_cout_presence": "à la fois le coût ET la fourchette de coûts sont déclarés. Merci de renseigner soit 'cout', soit 'cout_min' et 'cout_max'",
              "error_travaux_cout_cumule_fourchette": "une fourchette de coûts cumulés est mal déclarée, puisque l'une des deux balises nécessaires : 'cout_cumule_max', 'cout_cumule_min', est manquante",
              "error_travaux_cout_cumule_missing": "aucun coûts cumulés n'est déclaré. Merci de renseigner soit 'cout_cumule', soit 'cout_cumule_min' et 'cout_cumule_max'",
              "error_travaux_cout_cumule_presence": "à la fois le coût cumulé ET la fourchette de coûts cumulés sont déclarés. Merci de renseigner soit 'cout_cumule', soit 'cout_cumule_min' et 'cout_cumule_max'",
              "error_travaux_cout_order": "'cout_min' est supérieur à 'cout_max'",
              "error_travaux_cout_cumule_order": "'cout_cumule_min' est supérieur à 'cout_cumule_max'",
              "error_missing_dpe_version": "la balise 'enum_version_dpe_id' est manquante dans le XML, or elle est obligatoire à compter du 1er juillet 2024",
              "warning_missing_dpe_version": "la balise 'enum_version_dpe_id' est manquante dans le XML, or elle est obligatoire à compter du 1er juillet 2024",
              "warning_compatibility_dpe_audit_version": "le numéro de version dpe n'est pas compatible avec la version de l'audit sélectionnée",
              "error_compatibility_dpe_audit_version": "le numéro de version dpe n'est pas compatible avec la version de l'audit sélectionnée",
              "error_dpe_2_4_date": "le numéro de version dpe '2.4' ne peut pas être utilisé avant le 1er juillet 2024 dans l'audit",
              "error_wrong_sum_gain": "un scénario a des sommes des gains d'énergie, de carbone ou de factures, qui ne sont pas strictement négatives",
              "error_travaux_autre_rate": "le taux d'utilisation de l'option 'autre' (ID 10 pour les lots ou ID 24 pour les types) pour définir les travaux est trop important (> 90%).",
              "error_incoherent_ef_conso_surface": "la consommation d’énergie finale rapportée à la surface n’est pas cohérente avec la consommation totale et la surface de référence.",
              "error_incoherent_ep_conso_surface": "la consommation d’énergie primaire rapportée à la surface n’est pas cohérente avec la consommation totale et la surface de référence.",
              "error_incoherent_emission_ges_surface": "les émissions de GES rapportées à la surface ne sont pas cohérentes avec les émissions totales et la surface de référence.",
              "error_surface_habitable_exceeds_building": "la surface habitable du logement dépasse ou est égale à la surface habitable de l'immeuble",
              "warning_nombre_appartement": "le nombre d'appartement est potentiellement anormal",
              "error_scenario_copro_missing": "le scénario 'audit copro principal' (enum_scenario_id = 7), requis pour un audit de type copropriété (enum_modele_audit_id = 3), est manquant",
              "error_scenario_copro_forbidden": "le scénario 'audit copro principal' (enum_scenario_id = 7) ne doit pas être présent dans un audit qui n’est pas de type copropriété (enum_modele_audit_id ≠ 3)",
              "error_scenario_non_copro_forbidden": "les scénarios 'multi étapes principal' (enum_scenario_id = 1) ou 'en une étape principal' (enum_scenario_id = 2) ne doivent pas être présents dans un audit de type copropriété (enum_modele_audit_id = 3)",
              "error_derogation_technique_copro": "la dérogation technique doit être 'non applicable' (id 3) pour un audit copropriété",
              "error_derogation_economique_copro": "la dérogation économique doit être 'non applicable' (id 4) pour un audit copropriété",
              "error_derogation_technique_non_copro": "la dérogation technique 'non applicable - audit copro' (id 3) ne doit pas être utilisée pour un audit non copropriété",
              "error_derogation_economique_non_copro": "la dérogation économique 'non applicable - audit copro' (id 4) ne doit pas être utilisée pour un audit non copropriété"
              }

msg_importance = {
    "blocker": 'bloquant',
    "blocker_as_warning": 'bloquant_avertissement',
    "critical": "critique",
    'major': 'majeur',
    'minor': 'mineur',
}
